# Converted from Impro-Visor (js) vers 0.1.0
# Impro-Visor is GPL-3, copyright 2005-2017 Robert Keller and Harvey Mudd College
# see: https://github.com/Impro-Visor/Impro-Visor
- [title, Sad, Cadence, 2]
- [composer]
- [show]
- [year]
- [comments]
- [meter, 4, 4]
- [key, 0]
- [tempo, 160]
- [volume, 127]
- [playback-transpose, 0]
- [chord-font-size, 16]
- [bass-instrument, 33]
- [bass-volume, 50]
- [drum-volume, 36]
- [chord-volume, 54]
- [breakpoint, 54]
- [layout]
- [style, swing, [swing, 0.67], [comp-swing, 0.67], [bass-high, g-], [bass-low, c---], [bass-base, e--], [chord-high, a], [chord-low, d-], [chord-base, c-, e-, g-]]
- [part, [type, chords], [title], [composer], [instrument, 0], [volume, 65], [key, 0]]
- [section, [style, swing], [body, "Dm7b5 | G7alt | Cm69 | / | \n\n"]]
- [part, [type, melody], [title], [composer], [instrument, 11], [volume, 85], [key, 0], [stave, treble], [body, 'r1+1+1+1 ']]
