# Converted from Impro-Visor src on 2022-07-13T16:27:29.312Z
# Impro-Visor is GPL-3, copyright 2005-2017 Robert Keller and Harvey Mudd College
# see: https://github.com/Impro-Visor/Impro-Visor
- [title, Tell, Me, That, You, Love, 'Me,', Junie, Moon]
- [composer, Philip, Springer]
- [show, 'film:', Tell, Me, That, You, Love, 'Me,', Junie, Moon]
- [year, 1970]
- [comments]
- [meter, 4, 4]
- [key, 2]
- [tempo, 132]
- [volume, 127]
- [playback-transpose, 0]
- [bass-instrument, 33]
- [bass-volume, 60]
- [drum-volume, 60]
- [chord-volume, 60]
- [breakpoint, 54]
- [layout]
- [style, ballad, [swing, 0.67], [comp-swing, 0.67], [bass-high, g-], [bass-low, g---], [bass-base, c--], [chord-high, b], [chord-low, b--], [chord-base, c-, e-, g-]]
- [part, [type, chords], [title], [composer], [instrument, 0], [volume, 65], [key, 2]]
- [section, [style, ballad], [body, "D | A6 | Bm | D | \nD6 | A7sus | A7 | Bbm Bb / / | \nBbM7 | A7sus | A7 | D | \nA6 | Bm | D | D6 | \nA7sus | A7 | Bbm Bb / / | BbM7 | \nEbM7 | / | Ab6 | / | \nEbM7 | / | Asus4 | / | \nD | A6 | Bm | D | \nD6 | A7sus | A7 | Bbm Bb / / | \nA7sus | D | \n"]]
- [part, [type, melody], [title], [composer], [instrument, 11], [volume, 85], [key, 2], [stave, treble], [body, "f#2 r1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+2\n"]]
