# Converted from Impro-Visor src on 2022-07-13T16:27:29.831Z
# Impro-Visor is GPL-3, copyright 2005-2017 Robert Keller and Harvey Mudd College
# see: https://github.com/Impro-Visor/Impro-Visor
- [title, Your, Cheatin', Heart]
- [composer, Hank, Williams]
- [show]
- [year]
- [comments]
- [meter, 4, 4]
- [key, 0]
- [tempo, 120]
- [volume, 127]
- [playback-transpose, 0]
- [bass-instrument, 33]
- [bass-volume, 60]
- [drum-volume, 60]
- [chord-volume, 60]
- [breakpoint, 54]
- [layout]
- [style, shuffle, [swing, 0.67], [comp-swing, 0.67], [bass-high, g-], [bass-low, g---], [bass-base, c--], [chord-high, a], [chord-low, c-], [chord-base, c-, e-, g-]]
- [part, [type, chords], [title], [composer], [instrument, 0], [volume, 65], [key, 0]]
- [section, [style, shuffle], [body, "C | C7 | F | / | \nG7 | / | C | / G7 | \nC | C7 | F | / | \nG7 | / | C F | C C7 / / | \nF | / | C | / | \nD7 | / | G7 | / | \nC | C7 | F | / | \nG7 | / | C F | C G7 | \n\n"]]
- [part, [type, melody], [title], [composer], [instrument, 11], [volume, 85], [key, 0], [stave, treble], [body, "e1+4 \n r1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+2+4\n"]]
