# Converted from Impro-Visor src on 2022-07-13T16:27:30.745Z
# Impro-Visor is GPL-3, copyright 2005-2017 Robert Keller and Harvey Mudd College
# see: https://github.com/Impro-Visor/Impro-Visor
- [title, Idioms, in, Grammar, Illustration]
- [composer]
- [show]
- [year]
- [comments]
- [meter, 4, 4]
- [key, 0]
- [tempo, 162]
- [volume, 80]
- [playback-transpose, 0]
- [chord-font-size, 16]
- [bass-instrument, 33]
- [bass-volume, 46]
- [drum-volume, 60]
- [chord-volume, 68]
- [breakpoint, 54]
- [layout, 4]
- [roadmap-layout, 8]
- [style, swing, [swing, 0.67], [comp-swing, 0.67], [bass-high, g-], [bass-low, g---], [bass-base, c--], [chord-high, a], [chord-low, c-], [chord-base, c-, e-, g-]]
- [part, [type, chords], [title, Untitled, Part], [composer], [instrument, 0], [volume, 65], [key, 0]]
- [section, [style, swing], [body, "C7 | / | F7 | / | \nBb7 | / | Eb7 | / | \nAb7 | / | Db7 | / | \nGb7 | / | B7 | / | \nE7 | / | A7 | / | \nD7 | / | G7 | / | \n\n"]]
- [part, [type, melody], [title, Chorus, 1], [composer], [instrument, 56], [volume, 85], [key, 0], [stave, treble], [body, 'r1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1 ']]
